### ISSUE TITLE
error with allhic optimise post rescue

### ISSUE THREAD

**Issue by rahulvrane** [tangerzhang/ALLHiC#116]
Hello 

We are trying to assemble a plan genome and used the ragoo2ALLHiC.py script to do this. It started with ARIMA - so had to edit the restriction components to compensate, however, we keep getting this error for all groups during optimisation. Please could I get your help with the same? 

This error doesnt come when we run optimise after allhic_partition.

```
14:24:15 readRE | NOTICE  Parse REfile `group2.txt`
14:24:15 readClmLines | NOTICE  Parse clmfile `sample.clean.clm`
14:24:55 reportActive | NOTICE  Active tigs: 5195 (length=357272496)
14:34:21 flipLog | NOTICE  FLIPALL: -2398243.10805 => -2397986.21621 ACCEPT
14:34:21 Run | NOTICE  Optimization history logged to `group2.tour`
14:34:21 GARun | NOTICE  GA initialized (npop: 100, ngen: 10000, mu: 0.20, rng: 42, break: 10000000)
panic: interface conversion: eaopt.Genome is nil, not allhic.Tour

goroutine 1 [running]:
github.com/tanghaibao/allhic.(*CLM).GARun.func2(0xc0001840c0)
        /Users/bao/go/src/github.com/tanghaibao/allhic/evaluate.go:314 +0x3e4
github.com/MaxHalford/eaopt.(*GA).init(0xc0001840c0, 0xc000553920, 0x8d11c37f27, 0x5)
        /Users/bao/go/src/github.com/MaxHalford/eaopt/ga.go:74 +0x5bc
github.com/MaxHalford/eaopt.(*GA).Minimize(0xc0001840c0, 0xc000553920, 0xc000131090, 0xc00015a050)
        /Users/bao/go/src/github.com/MaxHalford/eaopt/ga.go:146 +0x39
github.com/tanghaibao/allhic.(*CLM).GARun(0xc0001b2000, 0xc000ed8010, 0xc0001643f0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/bao/go/src/github.com/tanghaibao/allhic/evaluate.go:328 +0x5ad
github.com/tanghaibao/allhic.(*CLM).OptimizeOrdering(...)
        /Users/bao/go/src/github.com/tanghaibao/allhic/optimize.go:84
github.com/tanghaibao/allhic.(*Optimizer).Run(0xc0001643f0)
        /Users/bao/go/src/github.com/tanghaibao/allhic/optimize.go:67 +0x4d5
github.com/tanghaibao/allhic.init.1.func5(0xc000161b80, 0xc000158500, 0x2, 0x4)
        /Users/bao/go/src/github.com/tanghaibao/allhic/allhic.go:182 +0x1b2
github.com/spf13/cobra.(*Command).execute(0xc000161b80, 0xc0001584c0, 0x4, 0x4, 0xc000161b80, 0xc0001584c0)
        /Users/bao/go/src/github.com/spf13/cobra/command.go:833 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xe581e0, 0x1, 0x1, 0xaf9de0)
        /Users/bao/go/src/github.com/spf13/cobra/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/bao/go/src/github.com/spf13/cobra/command.go:867
github.com/tanghaibao/allhic.Execute(...)
        /Users/bao/go/src/github.com/tanghaibao/allhic/allhic.go:40
main.main()
        /Users/bao/code/allhic/cmd/main.go:19 `+0x6e
```

Thanks a ton!

**Comment by sc-zhang** [comment]
@rahulvrane would you please show me the full command and the orderings.list file which you used for ragoo2ALLHiC?
