### ISSUE TITLE
allhic build run error

### ISSUE THREAD

**Issue by christinawu2008** [tangerzhang/ALLHiC#12]
Hi there,

I got a run time error from building fasta step, details are below:

```
12:06:45 getFastaSizes | NOTICE  Parse FASTA file `MR_H.fasta`
12:06:48 mergeTours | NOTICE  Import `REduced.paired_only.srt.counts_GATC.12g10.tour` => g1
12:06:48 parseTourFile | NOTICE  Parse tour file `REduced.paired_only.srt.counts_GATC.12g10.tour`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x881785]

goroutine 1 [running]:
github.com/shenwei356/bio/seq.(*Seq).Length(...)
	/Users/bao/go/src/github.com/shenwei356/bio/seq/seq.go:75
_/Users/bao/code/allhic.(*OO).parseLastTour(0xc0000576e8, 0x7fff3eaa2e54, 0x46, 0xc038f95290, 0x2)
	/Users/bao/code/allhic/build.go:155 +0xf5
_/Users/bao/code/allhic.(*OO).mergeTours(0xc0000576e8, 0xc0000894f0, 0x1, 0x1)
	/Users/bao/code/allhic/build.go:136 +0x230
_/Users/bao/code/allhic.(*Builder).Run(0xc000057788)
	/Users/bao/code/allhic/build.go:124 +0x80
main.main.func5(0xc000110c60, 0xc000098f00, 0xc000110c60)
	/Users/bao/code/allhic/cmd/allhic.go:279 +0x234
github.com/urfave/cli.HandleAction(0x90f200, 0x9da348, 0xc000110c60, 0x0, 0xc000098f00)
	/Users/bao/go/src/github.com/urfave/cli/app.go:501 +0xc8
github.com/urfave/cli.Command.Run(0x9b70f6, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9bcac5, 0x14, 0x9d048a, ...)
	/Users/bao/go/src/github.com/urfave/cli/command.go:165 +0x459
github.com/urfave/cli.(*App).Run(0xc000124380, 0xc00009a000, 0x5, 0x5, 0x0, 0x0)
	/Users/bao/go/src/github.com/urfave/cli/app.go:259 +0x6bb
main.main()
	/Users/bao/code/allhic/cmd/allhic.go:400 +0xb31

```

There is no issues from the server side. Any ideas?

Thank you!
Chen

**Comment by tangerzhang** [comment]
Please use ALLHiC_build script instead of allhic build :-)

**Comment by christinawu2008** [comment]
@tangerzhang wondering if ALLHiC takes multiple digestions? i have GATC plus AATT...

if so how to set them? example:
```
allhic extract srt.bam ref.fasta --RE AATT
```

**Comment by tangerzhang** [comment]
No, the current version does not support multiple restriction sites.
