### ISSUE TITLE
ALLHiC_plot : AttributeError

### ISSUE THREAD

**Issue by Willtao2023** [tangerzhang/ALLHiC#170]
This my command: 
ALLHiC_plot -b sorted.bam -a groups.agp -l chrn.list -s 50k  -o ./heatmap-pdf 

error happened in step2 :Get signal matrix
[17:27:39] Step1: Get chromosome length
[17:27:39] Step2: Get signal matrix
Traceback (most recent call last):
  File "/newlustre/home/jfgui/Wangtao/software/ALLHiC/bin/ALLHiC_plot", line 250, in <module>
    ALLHiC_plot(bam, agp, chrlist, npzfile, minsize, binsize, outdir)
  File "/newlustre/home/jfgui/Wangtao/software/ALLHiC/bin/ALLHiC_plot", line 226, in ALLHiC_plot
    bin_offset_min_size, read_count_whole_genome_min_size = calc_read_count_per_min_size(chr_len_db, chr_order, bam, agp, min_size)
  File "/newlustre/home/jfgui/Wangtao/software/ALLHiC/bin/ALLHiC_plot", line 80, in calc_read_count_per_min_size
    ctg1 = line.reference_name
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'reference_name'

Thank you for your suggestions

**Comment by Willtao2023** [comment]
Problem had been solved when I installed the "pysam" software.
