### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JiaZhibo123** [tangerzhang/ALLHiC#79]
When I run "ALLHiC_plot sample.clean.bam groups.agp chrn.list 500k pdf", I met the mistake 
Traceback (most recent call last):
  File "/public/home/zbjia/soft/ALLHiC/bin/ALLHiC_plot", line 249, in <module>
    read_count_per_chr, read_count_whole_genome = calc_read_count_per_bin(chr_len_db, chr_order, read_on_chr, bin_size)
  File "/public/home/zbjia/soft/ALLHiC/bin/ALLHiC_plot", line 112, in calc_read_count_per_bin
    read_count_per_chr[chr1][pos1_index][pos2_index] += 1
IndexError: list index out of range

**Comment by sc-zhang** [comment]
If you run this script with python3, the result of round function may be unexpected, I've already fix this problem, you can update it, and try again to check if it works or not.

**Comment by JiaZhibo123** [comment]
My python vision is 3.83, which vision should I update?

**Comment by sc-zhang** [comment]
I mean I have made some changes in the script, so you can update the ALLHiC_plot and check if it works or not.

**Comment by JiaZhibo123** [comment]
ok,I copy "https://github.com/tangerzhang/ALLHiC/blob/master/bin/ALLHiC_plot" to my allhic/bin , met the same error

**Comment by sc-zhang** [comment]
Can you paste your list file and bin size here?

**Comment by JiaZhibo123** [comment]
list file is ?

**Comment by sc-zhang** [comment]
chrn.list

**Comment by JiaZhibo123** [comment]
chrn.list
group1	1010788464
group10	607078
group11	309303
group12	285840
group13	282637
group14	215647
group15	203962
group16	173060
group17	106304
group18	47972
group19	45951
group2	1104409
group3	639707
group4	626453
group5	514609
group6	434432
group7	377685
group8	354765
group9	347690
HiC_scaffold_1624	35015
HiC_scaffold_1443	112163
HiC_scaffold_785	181000
HiC_scaffold_1629	30275
HiC_scaffold_1078	445135
HiC_scaffold_1623	36113
HiC_scaffold_845	28000
HiC_scaffold_1628	32157
HiC_scaffold_1617	40664
HiC_scaffold_1622	37003
HiC_scaffold_1625	34558
HiC_scaffold_1636	15454
HiC_scaffold_52	16259
HiC_scaffold_1444	59064
HiC_scaffold_436	35591
HiC_scaffold_515	1000
HiC_scaffold_1074	32000
HiC_scaffold_1260	10946
HiC_scaffold_1630	26609
HiC_scaffold_1631	24996
HiC_scaffold_1618	40482
HiC_scaffold_1627	6040
HiC_scaffold_779	43000
HiC_scaffold_1619	38618
HiC_scaffold_173	31891
HiC_scaffold_135	25000
HiC_scaffold_965	1633033
HiC_scaffold_1620	38325
HiC_scaffold_1364	80066
HiC_scaffold_1621	37372
HiC_scaffold_180	34570
HiC_scaffold_1341	322749
HiC_scaffold_676	109592
HiC_scaffold_1363	88681
HiC_scaffold_546	85385
HiC_scaffold_1634	20763
HiC_scaffold_677	254408
HiC_scaffold_1626	2000
HiC_scaffold_1635	16644
HiC_scaffold_1632	22433
HiC_scaffold_1374	11522
HiC_scaffold_475	27468
HiC_scaffold_1633	21249
HiC_scaffold_540	17022
bin size   500k 
Thank you

**Comment by sc-zhang** [comment]
I added the exception check in the new version of script, and you can try it again, and check the log which printed by ALLHiC_plot and paste the lines with "Index error" here.

**Comment by JiaZhibo123** [comment]
[23826017.txt](https://github.com/tangerzhang/ALLHiC/files/5994551/23826017.txt)
[23826017 (2).txt](https://github.com/tangerzhang/ALLHiC/files/5994559/23826017.2.txt)

**Comment by JiaZhibo123** [comment]
[23826017.txt](https://github.com/tangerzhang/ALLHiC/files/5994564/23826017.txt)
[23826017 (2).txt](https://github.com/tangerzhang/ALLHiC/files/5994573/23826017.2.txt)

**Comment by sc-zhang** [comment]
1. you need install python module matplotlib
2. the bin size is too small for almost all chromosomes, and the first group is too large than others, maybe you need check if the assembly result is appropriated.
3.  you can use different chrn.list files contain different groups, and run ALLHiC_plot with different bin size for them.

**Comment by JiaZhibo123** [comment]
1.  I remove the group 1 from chrn list , no error report . The log file is 
python /public/home/zbjia/soft/ALLHiC/bin/ALLHiC_plot /public/home/zbjia/allhic/3008clean.bam /public/home/zbjia/allhic/hic/exgroup1/chrn.list 500k pdf
"Successfully completed.

Resource usage summary:

    CPU time :                                   0.17 sec.
    Max Memory :                                 14 MB
    Average Memory :                             14.00 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                5
    Run time :                                   2 sec.
    Turnaround time :                            3 sec.

The output (if any) follows:

This script is used to plot chromatin matrix for ALLHiC results
Usage: python /public/home/zbjia/soft/ALLHiC/bin/ALLHiC_plot <sam/bam file> <agp_file> <chr_list> <bin_size> <ext>
	<sam/bam_file> is the sam or bam file of mapping
	<agp_file> is the file created by allhic
	<chr_list> is the file containing chromosome ID and length
	<bin_size> is the bin size of heatmap, it can be a list splited by comma
	<ext> is the extention of plot, e.g. pdf


PS:

Read file <23826072.err> for stderr output of this job."
But I don't get any file.

2.I just run group 1, changing the bin size 1m, the output pdf is terrible .
![QAIA6DQ0%90K6DZQM(8HHGN](https://user-images.githubusercontent.com/67772967/108291766-af92ef80-718a-11eb-93e5-3146b3c872ee.png)

**Comment by sc-zhang** [comment]
You should remove HiC_scaffolds from chrn.list, and the heatmap of group1 may illustrate that the assembly of it is inappropriate.
For other groups, the second parameter of the script is agp file, and you did not provided it, so there is no any output, and the bin size 500k is too large for these groups, so you should use lower bin size and try again.
